import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Button } from './ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { Report } from '../types/financial';
import { Download, Play, Edit, Calendar, Zap } from 'lucide-react';

interface ReportingAutomationProps {
  reports: Report[];
  onDownloadReport?: (report: Report) => void;
  onScheduleReport?: (report: Report) => void;
  onEditReport?: (report: Report) => void;
}

export function ReportingAutomation({ 
  reports, 
  onDownloadReport, 
  onScheduleReport,
  onEditReport 
}: ReportingAutomationProps) {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Published': return 'default';
      case 'Draft': return 'secondary';
      case 'Scheduled': return 'outline';
      default: return 'default';
    }
  };

  const getTypeColor = (type: string) => {
    switch (type) {
      case 'Monthly': return 'bg-blue-100 text-blue-700';
      case 'Quarterly': return 'bg-purple-100 text-purple-700';
      case 'Annual': return 'bg-green-100 text-green-700';
      case 'Custom': return 'bg-orange-100 text-orange-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  return (
    <div className="space-y-6">
      <Card className="bg-gradient-to-r from-blue-50 to-purple-50 border-blue-200">
        <CardContent className="pt-6">
          <div className="flex items-start gap-4">
            <div className="bg-blue-600 p-3 rounded-lg">
              <Zap className="size-6 text-white" />
            </div>
            <div className="flex-1">
              <h3 className="mb-2">Power Automate Integration</h3>
              <p className="text-muted-foreground mb-4">
                Connect to Microsoft Power Automate to automatically generate and distribute reports on schedule. 
                Trigger workflows when invoices are created, budgets are exceeded, or custom conditions are met.
              </p>
              <div className="flex gap-2">
                <Button>
                  <Play className="size-4 mr-2" />
                  Configure Automation
                </Button>
                <Button variant="outline">
                  View Active Flows
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>Automated Reports</CardTitle>
          <Button>
            <Calendar className="size-4 mr-2" />
            Schedule New Report
          </Button>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Title</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Generated Date</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Next Run</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>{report.title}</TableCell>
                    <TableCell>
                      <span className={`px-2 py-1 rounded text-sm ${getTypeColor(report.type)}`}>
                        {report.type}
                      </span>
                    </TableCell>
                    <TableCell>{report.generatedDate}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        {report.generatedBy}
                        {report.generatedBy === 'System Auto' && (
                          <Zap className="size-4 text-blue-600" />
                        )}
                      </div>
                    </TableCell>
                    <TableCell>
                      {report.nextRun ? (
                        <div className="flex items-center gap-1 text-blue-600">
                          <Calendar className="size-4" />
                          {report.nextRun}
                        </div>
                      ) : (
                        <span className="text-muted-foreground">-</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <Badge variant={getStatusColor(report.status)}>
                        {report.status}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-2">
                        {report.status === 'Published' && (
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => onDownloadReport?.(report)}
                          >
                            <Download className="size-4" />
                          </Button>
                        )}
                        <Button 
                          size="sm" 
                          variant="outline"
                          onClick={() => onEditReport?.(report)}
                        >
                          <Edit className="size-4" />
                        </Button>
                        {report.status !== 'Scheduled' && (
                          <Button 
                            size="sm" 
                            variant="default"
                            onClick={() => onScheduleReport?.(report)}
                          >
                            <Calendar className="size-4" />
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Automation Workflows</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex items-center gap-3">
                  <div className="bg-green-100 p-2 rounded">
                    <CheckCircle className="size-4 text-green-600" />
                  </div>
                  <div>
                    <div>Monthly Budget Report</div>
                    <div className="text-sm text-muted-foreground">Runs 1st of every month</div>
                  </div>
                </div>
                <Badge>Active</Badge>
              </div>
              
              <div className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex items-center gap-3">
                  <div className="bg-green-100 p-2 rounded">
                    <CheckCircle className="size-4 text-green-600" />
                  </div>
                  <div>
                    <div>Invoice Overdue Alert</div>
                    <div className="text-sm text-muted-foreground">Checks daily</div>
                  </div>
                </div>
                <Badge>Active</Badge>
              </div>
              
              <div className="flex items-center justify-between p-3 border rounded-lg">
                <div className="flex items-center gap-3">
                  <div className="bg-green-100 p-2 rounded">
                    <CheckCircle className="size-4 text-green-600" />
                  </div>
                  <div>
                    <div>Budget Threshold Alert</div>
                    <div className="text-sm text-muted-foreground">Real-time monitoring</div>
                  </div>
                </div>
                <Badge>Active</Badge>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Power BI Integration</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <p className="text-muted-foreground">
                Connect to Power BI to access advanced analytics and create custom visualizations.
              </p>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-sm">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  Embedded reports enabled
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  Real-time data sync active
                </div>
                <div className="flex items-center gap-2 text-sm">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  Auto-refresh: Every 30 minutes
                </div>
              </div>
              <Button className="w-full" variant="outline">
                Open in Power BI
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function CheckCircle({ className }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  );
}
